# Generated by Django 6.0.3 on 2026-04-07 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='machines.machine', verbose_name='Машина')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.maintenancetype', verbose_name='Вид ТО')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances_as_organization', to='reference_books.servicecompany', verbose_name='Организация, проводившая ТО')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
                'ordering': ['-maintenance_date'],
            },
        ),
    ]
