# Generated by Django 6.0.3 on 2026-04-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_failure_node_and_more'),
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='repair_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.repairmethod', verbose_name='Способ восстановления'),
        ),
    ]
